/* DO NOT EDIT THIS FILE - it is machine generated */
/* Generated for class com.naryx.tagfusion.cfm.sql.ODBCNativeLib */
/* Generated from ODBCNativeLib.java*/

#ifndef _Included_com_naryx_tagfusion_cfm_sql_ODBCNativeLib
#define _Included_com_naryx_tagfusion_cfm_sql_ODBCNativeLib
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_naryx_tagfusion_cfm_sql_ODBCNativeLib
 * Method:    getOdbcDataSources
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_naryx_tagfusion_cfm_sql_ODBCNativeLib_getOdbcDataSources
	(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
