language: java
script: ant -buildfile build/build.xml clean war-with-manual ready2run
if: tag IS blank

after_success:
  # Set up git user name and tag this commit
  - git config --local user.name "openbdbuild"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: 
  - build/targets/openbd.war
  - build/targets/OpenBlueDragon.jar
  - build/targets/jetty-openbd.zip
  skip_cleanup: true
  on:
    tags: false
    branch: master
