language: java
script: ant -buildfile build/build.xml clean war-with-manual
if: tag IS blank

after_success:
  # Set up git user name and tag this commit
  - echo "after_success started"
  - git config --local user.name "openbdbuild"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - git remote add origin-token https://$GITHUB_OAUTH_TOKEN@github.com/OpenBD/openbd-core.git
  - git push --set-upstream origin-token --tags
  - echo "after_success completed"
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "build/targets/openbd.war"
  skip_cleanup: true
  on:
    tags: true
