/* DO NOT EDIT THIS FILE - it is machine generated */
/* Generated for class com.naryx.tagfusion.cfx.CFXNativeLib */
/* Generated from CFXNativeLib.java*/

#ifndef _Included_com_naryx_tagfusion_cfx_CFXNativeLib
#define _Included_com_naryx_tagfusion_cfx_CFXNativeLib
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_naryx_tagfusion_cfx_CFXNativeLib
 * Method:    processRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/naryx/tagfusion/cfx/sessionRequest;Lcom/naryx/tagfusion/cfx/sessionResponse;Z)V
 */
JNIEXPORT void JNICALL Java_com_naryx_tagfusion_cfx_CFXNativeLib_processRequest
	(JNIEnv *, jclass, jstring, jstring, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
