/* 
 *  Copyright (C) 2000 - 2008 TagServlet Ltd
 *
 *  This file is part of Open BlueDragon (OpenBD) CFML Server Engine.
 *  
 *  OpenBD is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  Free Software Foundation,version 3.
 *  
 *  OpenBD is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with OpenBD.  If not, see http://www.gnu.org/licenses/
 *  
 *  Additional permission under GNU GPL version 3 section 7
 *  
 *  If you modify this Program, or any covered work, by linking or combining 
 *  it with any of the JARS listed in the README.txt (or a modified version of 
 *  (that library), containing parts covered by the terms of that JAR, the 
 *  licensors of this Program grant you additional permission to convey the 
 *  resulting work. 
 *  README.txt @ http://www.openbluedragon.org/license/README.txt
 *  
 *  http://www.openbluedragon.org/
 */

/* Generated By:JavaCC: Do not edit this line. selectSQLParserConstants.java */
package com.naryx.tagfusion.cfm.queryofqueries;

public interface selectSQLParserConstants {

  int EOF = 0;
  int SELECT = 6;
  int FROM = 7;
  int WHERE = 8;
  int ORDER = 9;
  int BY = 10;
  int GROUP = 11;
  int HAVING = 12;
  int NOT = 13;
  int IS = 14;
  int TRUE = 15;
  int FALSE = 16;
  int AS = 17;
  int OR = 18;
  int AND = 19;
  int AVG = 20;
  int SUM = 21;
  int MIN = 22;
  int MAX = 23;
  int COUNT = 24;
  int DISTINCT = 25;
  int BETWEEN = 26;
  int LIKE = 27;
  int ALL = 28;
  int ASC = 29;
  int DESC = 30;
  int UNKNOWN = 31;
  int NULL = 32;
  int IN = 33;
  int UNION = 34;
  int ABSOLUTE = 35;
  int ACTION = 36;
  int ADD = 37;
  int ALLOCATE = 38;
  int ALTER = 39;
  int ANY = 40;
  int ARE = 41;
  int ASSERTION = 42;
  int AT = 43;
  int AUTHORIZATION = 44;
  int BEGIN = 45;
  int BIT = 46;
  int BIT_LENGTH = 47;
  int BOTH = 48;
  int CASCADE = 49;
  int CASCADED = 50;
  int CASE = 51;
  int CAST = 52;
  int CATALOG = 53;
  int CHAR = 54;
  int CHARACTER = 55;
  int CHARACTER_LENGTH = 56;
  int CHAR_LENGTH = 57;
  int CHECK = 58;
  int CLOSE = 59;
  int COALESCE = 60;
  int COLLATE = 61;
  int COLLATION = 62;
  int COLUMN = 63;
  int COMMIT = 64;
  int CONNECT = 65;
  int CONNECTION = 66;
  int CONSTRAINT = 67;
  int CONSTRAINTS = 68;
  int CONTINUE = 69;
  int CONVERT = 70;
  int CORRESPONDING = 71;
  int CREATE = 72;
  int CROSS = 73;
  int CURRENT = 74;
  int CURRENT_DATE = 75;
  int CURRENT_TIME = 76;
  int CURRENT_TIMESTAMP = 77;
  int CURRENT_USER = 78;
  int CURSOR = 79;
  int DATE = 80;
  int DAY = 81;
  int DEALLOCATE = 82;
  int DEC = 83;
  int DECIMAL = 84;
  int DECLARE = 85;
  int DEFAULT_RESERVED = 86;
  int DEFERRABLE = 87;
  int DEFERRED = 88;
  int DELETE = 89;
  int DESCRIBE = 90;
  int DESCRIPTOR = 91;
  int DIAGNOSTICS = 92;
  int DISCONNECT = 93;
  int DOMAIN = 94;
  int DOUBLE = 95;
  int DROP = 96;
  int ELSE = 97;
  int END = 98;
  int ENDEXEC = 99;
  int ESCAPE = 100;
  int EXCEPT = 101;
  int EXCEPTION = 102;
  int EXEC = 103;
  int EXECUTE = 104;
  int EXISTS = 105;
  int EXTERNAL = 106;
  int EXTRACT = 107;
  int FETCH = 108;
  int FIRST = 109;
  int FLOAT = 110;
  int FOR = 111;
  int FOREIGN = 112;
  int FOUND = 113;
  int FULL = 114;
  int GET = 115;
  int GLOBAL = 116;
  int GO = 117;
  int GOTO = 118;
  int GRANT = 119;
  int HOUR = 120;
  int IDENTITY = 121;
  int IMMEDIATE = 122;
  int INDICATOR = 123;
  int INITIALLY = 124;
  int INNER = 125;
  int INPUT = 126;
  int INSENSITIVE = 127;
  int INSERT = 128;
  int INT = 129;
  int INTEGER = 130;
  int INTERSECT = 131;
  int INTERVAL = 132;
  int INTO = 133;
  int ISOLATION = 134;
  int JOIN = 135;
  int KEY = 136;
  int LANGUAGE = 137;
  int LAST = 138;
  int LEADING = 139;
  int LEFT = 140;
  int LEVEL = 141;
  int LOCAL = 142;
  int LOWER = 143;
  int MATCH = 144;
  int MINUTE = 145;
  int MODULE = 146;
  int MONTH = 147;
  int NAMES = 148;
  int NATIONAL = 149;
  int NATURAL = 150;
  int NCHAR = 151;
  int NEXT = 152;
  int NO = 153;
  int NULLIF = 154;
  int NUMERIC = 155;
  int OCTET_LENGTH = 156;
  int OF = 157;
  int ON = 158;
  int ONLY = 159;
  int OPEN = 160;
  int OPTION = 161;
  int OUTER = 162;
  int OUTPUT = 163;
  int OVERLAPS = 164;
  int PAD = 165;
  int PARTIAL = 166;
  int POSITION = 167;
  int PRECISION = 168;
  int PREPARE = 169;
  int PRESERVE = 170;
  int PRIMARY = 171;
  int PRIOR = 172;
  int PRIVILEGES = 173;
  int PROCEDURE = 174;
  int PUBLIC = 175;
  int READ = 176;
  int REAL = 177;
  int REFERENCES = 178;
  int RELATIVE = 179;
  int RESTRICT = 180;
  int REVOKE = 181;
  int RIGHT = 182;
  int ROLLBACK = 183;
  int ROWS = 184;
  int SCHEMA = 185;
  int SCROLL = 186;
  int SECOND = 187;
  int SECTION = 188;
  int SESSION_USER = 189;
  int SET = 190;
  int SMALLINT = 191;
  int SOME = 192;
  int SPACE = 193;
  int SQL = 194;
  int SQLCODE = 195;
  int SQLERROR = 196;
  int SQLSTATE = 197;
  int SUBSTRING = 198;
  int SYSTEM_USER = 199;
  int TABLE = 200;
  int TEMPORARY = 201;
  int THEN = 202;
  int TIME = 203;
  int TIMESTAMP = 204;
  int TIMEZONE_HOUR = 205;
  int TIMEZONE_MINUTE = 206;
  int TO = 207;
  int TRAILING = 208;
  int TRANSACTION = 209;
  int TRANSLATE = 210;
  int TRANSLATION = 211;
  int TRIM = 212;
  int UNIQUE = 213;
  int UPDATE = 214;
  int UPPER = 215;
  int USAGE = 216;
  int USER = 217;
  int USING = 218;
  int VALUE = 219;
  int VALUES = 220;
  int VARCHAR = 221;
  int VARYING = 222;
  int VIEW = 223;
  int WHEN = 224;
  int WHENEVER = 225;
  int WITH = 226;
  int WORK = 227;
  int WRITE = 228;
  int YEAR = 229;
  int ZONE = 230;
  int INTEGER_LITERAL = 231;
  int DECIMAL_LITERAL = 232;
  int FLOATING_POINT_LITERAL = 233;
  int EXPONENT = 234;
  int STRING_LITERAL = 235;
  int ESCAPE_SEQA = 236;
  int BOOLEAN_LITERAL = 237;
  int IDENTIFIER = 238;
  int LETTER = 239;
  int DIGIT = 240;
  int OPENPAREN = 241;
  int CLOSEPAREN = 242;
  int LBRACE = 243;
  int RBRACE = 244;
  int LBRACKET = 245;
  int RBRACKET = 246;
  int SEMICOLON = 247;
  int COLON = 248;
  int COMMA = 249;
  int QUESTION = 250;
  int EQ = 251;
  int ASTERISK = 252;
  int LTE = 253;
  int GTE = 254;
  int GT = 255;
  int LT = 256;
  int NEQ = 257;
  int NEQ2 = 258;
  int DOT = 259;
  int PLUS = 260;
  int MINUS = 261;
  int SLASH = 262;
  int BSLASH = 263;
  int POWER = 264;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"order\"",
    "\"by\"",
    "\"group\"",
    "\"having\"",
    "\"not\"",
    "\"is\"",
    "\"true\"",
    "\"false\"",
    "\"as\"",
    "\"or\"",
    "\"and\"",
    "\"avg\"",
    "\"sum\"",
    "\"min\"",
    "\"max\"",
    "\"count\"",
    "\"distinct\"",
    "\"between\"",
    "\"like\"",
    "\"all\"",
    "\"asc\"",
    "\"desc\"",
    "\"unknown\"",
    "\"null\"",
    "\"in\"",
    "\"union\"",
    "\"absolute\"",
    "\"action\"",
    "\"add\"",
    "\"allocate\"",
    "\"alter\"",
    "\"any\"",
    "\"are\"",
    "\"assertion\"",
    "\"at\"",
    "\"authorization\"",
    "\"begin\"",
    "\"bit\"",
    "\"bit_length\"",
    "\"both\"",
    "\"cascade\"",
    "\"cascaded\"",
    "\"case\"",
    "\"cast\"",
    "\"catalog\"",
    "\"char\"",
    "\"character\"",
    "\"character_length\"",
    "\"char_length\"",
    "\"check\"",
    "\"close\"",
    "\"coalesce\"",
    "\"collate\"",
    "\"collation\"",
    "\"column\"",
    "\"commit\"",
    "\"connect\"",
    "\"connection\"",
    "\"constraint\"",
    "\"constraints\"",
    "\"continue\"",
    "\"convert\"",
    "\"corresponding\"",
    "\"create\"",
    "\"cross\"",
    "\"current\"",
    "\"current_date\"",
    "\"current_time\"",
    "\"current_timestamp\"",
    "\"current_user\"",
    "\"cursor\"",
    "\"date\"",
    "\"day\"",
    "\"deallocate\"",
    "\"dec\"",
    "\"decimal\"",
    "\"declare\"",
    "\"default\"",
    "\"deferrable\"",
    "\"deferred\"",
    "\"delete\"",
    "\"describe\"",
    "\"descriptor\"",
    "\"diagnostics\"",
    "\"disconnect\"",
    "\"domain\"",
    "\"double\"",
    "\"drop\"",
    "\"else\"",
    "\"end\"",
    "\"end-exec\"",
    "\"escape\"",
    "\"except\"",
    "\"exception\"",
    "\"exec\"",
    "\"execute\"",
    "\"exists\"",
    "\"external\"",
    "\"extract\"",
    "\"fetch\"",
    "\"first\"",
    "\"float\"",
    "\"for\"",
    "\"foreign\"",
    "\"found\"",
    "\"full\"",
    "\"get\"",
    "\"global\"",
    "\"go\"",
    "\"goto\"",
    "\"grant\"",
    "\"hour\"",
    "\"identity\"",
    "\"immediate\"",
    "\"indicator\"",
    "\"initially\"",
    "\"inner\"",
    "\"input\"",
    "\"insensitive\"",
    "\"insert\"",
    "\"int\"",
    "\"integer\"",
    "\"intersect\"",
    "\"interval\"",
    "\"into\"",
    "\"isolation\"",
    "\"join\"",
    "\"key\"",
    "\"language\"",
    "\"last\"",
    "\"leading\"",
    "\"left\"",
    "\"level\"",
    "\"local\"",
    "\"lower\"",
    "\"match\"",
    "\"minute\"",
    "\"module\"",
    "\"month\"",
    "\"names\"",
    "\"national\"",
    "\"natural\"",
    "\"nchar\"",
    "\"next\"",
    "\"no\"",
    "\"nullif\"",
    "\"numeric\"",
    "\"octet_length\"",
    "\"of\"",
    "\"on\"",
    "\"only\"",
    "\"open\"",
    "\"option\"",
    "\"outer\"",
    "\"output\"",
    "\"overlaps\"",
    "\"pad\"",
    "\"partial\"",
    "\"position\"",
    "\"precision\"",
    "\"prepare\"",
    "\"preserve\"",
    "\"primary\"",
    "\"prior\"",
    "\"privileges\"",
    "\"procedure\"",
    "\"public\"",
    "\"read\"",
    "\"real\"",
    "\"references\"",
    "\"relative\"",
    "\"restrict\"",
    "\"revoke\"",
    "\"right\"",
    "\"rollback\"",
    "\"rows\"",
    "\"schema\"",
    "\"scroll\"",
    "\"second\"",
    "\"section\"",
    "\"session_user\"",
    "\"set\"",
    "\"smallint\"",
    "\"some\"",
    "\"space\"",
    "\"sql\"",
    "\"sqlcode\"",
    "\"sqlerror\"",
    "\"sqlstate\"",
    "\"substring\"",
    "\"system_user\"",
    "\"table\"",
    "\"temporary\"",
    "\"then\"",
    "\"time\"",
    "\"timestamp\"",
    "\"timezone_hour\"",
    "\"timezone_minute\"",
    "\"to\"",
    "\"trailing\"",
    "\"transaction\"",
    "\"translate\"",
    "\"translation\"",
    "\"trim\"",
    "\"unique\"",
    "\"update\"",
    "\"upper\"",
    "\"usage\"",
    "\"user\"",
    "\"using\"",
    "\"value\"",
    "\"values\"",
    "\"varchar\"",
    "\"varying\"",
    "\"view\"",
    "\"when\"",
    "\"whenever\"",
    "\"with\"",
    "\"work\"",
    "\"write\"",
    "\"year\"",
    "\"zone\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"\\\'\\\'\"",
    "<BOOLEAN_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"?\"",
    "\"=\"",
    "\"*\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"<\"",
    "\"<>\"",
    "\"!=\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"\\\\\"",
    "\"^\"",
  };

}
